name: Build and Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build x86 (32-bit)
        run: make ARCH=i386

      - name: Build x86_64 (64-bit)
        run: make ARCH=amd64

      - name: Build ARMv6
        run: make ARCH=armv6

      - name: Build ARMv7
        run: make ARCH=armv7

      - name: Build ARM64
        run: make ARCH=arm64

      # Add more build steps for other architectures as needed

      - name: Build for Linux
        run: make PLATFORM=linux

      - name: Build for macOS
        run: make PLATFORM=darwin

      - name: Build for Windows
        run: make PLATFORM=windows

      # Add more build steps for other platforms as needed

      - name: Package distribution
        run: |
          # Perform packaging steps here
          # For example, create a tarball or zip file

      - name: Publish distribution
        uses: actions/upload-release-asset@v1
        with:
          asset_path: |
            # Specify the path to the packaged distribution file
          release_id: ${{ github.event.release.id }}
          asset_name: dns2tcp-distribution

